title: CroDev's blog 
baseurl: "" 
url: "https://crodevs.github.io" 
description: >- 
  Bits from a software developer's brain
github_username:  crodevs
email: carson.rohan@gmail.com

# Build settings
theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
