title: Crodev's Bits
baseurl: "" 
url: "https://crodevs.github.io" 
port: 4000
description: >- 
  bits from a software developer's brain
github_username:  crodevs
repository: crodevs/crodevs.github.io
email: carson.rohan@gmail.com
include: [_pages]

# Build settings
markdown: kramdown
highlighter: rouge

remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      is_post: true
      layout: "post"
      permalink: /blog/:title
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      is_post: false
      layout: "page"
