title: CroDev Bits
baseurl: "" 
url: "https://crodevs.github.io" 
port: 4000
description: >- 
  Bits from a software developer's brain
github_username:  crodevs
email: carson.rohan@gmail.com
include: [_pages]

# Build settings
markdown: kramdown

remote_theme: jekyll/minima

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      is_post: true
      layout: "post"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      is_post: false
      layout: "page"
