title: CroDev's blog 
baseurl: "" 
url: "https://crodevs.github.io" 
description: >- 
  Bits from a software developer's brain
github_username:  crodevs
email: carson.rohan@gmail.com

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tagging-related_posts

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
